INSERT INTO TVSERIES(id,title,rating,genre,channel,grade,language,summary,image) VALUES
(1,'Breaking Bad','9.9',2,'AMC',1,1,'The movie El Camino is on October 10, yeah bitch!','brba.jpg'),
(2,'Game of Thrones','9.8',9,'HBO',1,1,'Cripple with useless powers becomes king. ¯\_(ツ)_/¯','got.jpeg'),
(3,'Ang Probinsiyano','0',2,'ABS-CBN',1,0,'An immortal cop fights crimes with guest stars.','probin.jpg'),
(4,'Descendants of the Sun','9.3',8,'KBS',1,2,'Song-Song got married then divorced. ¯\_(ツ)_/¯','dots.jpg'),
(5,'This is US','8.1',8,'KBS',1,2,'Mandy Moore becomes mother of triplets with struggles in life.','us.jpg'),
(6,'Stranger Things','8.5',1,'Netflix',1,2,'A girl with powers kills the demogorgon','st.jpg'),
(7,'Thirteen reasons why','7.4',7,'KBS',1,2,'13 reasons why not.','13rw.jpg'),
(8,'FRIENDS','10.0',11,'KBS',1,2,'Still in bed at 10, work began at 8. The best!','friends.jpg'),
(9,'Kadenang Ginto','6.7',8,'KBS',1,0,'Two women compete to become the best meme.','kadgin.jpg'),
(10,'Big Bang Theory','8.3',11,'KBS',1,2,'Bazinga!','bigbang.jpg'),
(11,'Ika-anim na Utos','7.8',8,'XXX',1,0,'Two women fight to death using one-day old eggs.','utos.jpg'),
(12,'The Golden Girls','8.4',11,'XXX',2,1,'Four women face the joyful and poignant realities of their golden years.','tgg.jpg'),
(13,'The Killer Bride','9.2',3,'XXX',1,0,'A killed bride later becomes the killer.','tkb.jpg'),
(14,'Meteor Garden','7.0',5,'XXX',1,2,'A girl chases a bus while carrying oranges.','meteor.jpg'),
(15,'The Handmaid''s Tale','6.5',8,'HBO',1,1,'Women called ''handmaids'' bear children for the barren wealthy.','hmt.jpg'),
(16,'Mind Hunter','9.1',10,'XXX',1,2,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...','mh.jpg'),
(17,'True Detective','8.3',10,'XXX',1,1,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...','trued.jpg'),
(18,'Money Heist','7.0',2,'XXX',1,1,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...','moneyh.jpg'),
(19,'Orphan Black','6.0',1,'XXX',1,1,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...','orphan.jpg'),
(20,'Kingdom','6.1',6,'XXX',1,2,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...','kingdom.jpg'),
(21,'Westworld','7.9',1,'XXX',1,1,'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt...','westw.jpg');